
number width = 20
boolean background = true

def earlyUpdate() (
  local f @= utils.getMain()
  
  local comp = compiler.getAppropriateCompiler(open(f, [1])[1])
  self.comp @= comp
  self.enabled = f != null and utils.canRun(f) and comp != null
)

def update() (
  goto frame.left + 15 0
  icon icons.build .6
  
  if self.hovered (
    cursor "pointer"
    if self.clicked (
      void self.comp.build(utils.folderUuidToPath(state.folder), utils.getMain())
    )
  )
)