
number width = 20
boolean background = true
    
def earlyUpdate() (
  local f @= utils.getMain()
  
  self.enabled = f != null and utils.canRun(f)
)

def update() (
  goto 0 0
  icon icons.play .6
  
  if self.hovered (
    cursor "pointer"
    if self.clicked (
      local f @= utils.getMain()
      if f != null (
        file "open" f
        file "start"
        file "close"
      )
    )
  )
)
